lyrebird_metapackage: "/mnt/weka/scratch/microbiome/woodcrob/lyrebird_v0.3.1_phrog_v4.1_metapackage_20250720.smpkg.zb"
samples_csv: "sample_lists/lyrebird_20260316"
results_dir: "results/lyrebird_20260316"
