apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sandpiper4
  region: us-east-1

managedNodeGroups:
  - name: io-mach6
    instanceType: c7a.12xlarge
    minSize: 0
    maxSize: 100
    desiredCapacity: 2
    volumeSize: 550
    volumeType: gp3
    volumeIOPS: 6000
    volumeThroughput: 300
    spot: true
