apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sandpiper2026
  region: us-east-1

managedNodeGroups:
  - name: nodegroup1
    instanceType: c7a.12xlarge
    minSize: 0
    maxSize: 50
    desiredCapacity: 40
    volumeSize: 600
    volumeType: gp3
    volumeIOPS: 6000
    volumeThroughput: 1000
    spot: true
